/**
 * Generates docs/mechanisms.md from the diagram models so the prose beside
 * each picture (caption, verify line, claims, assurance) cannot drift from
 * what the app prints. JSX-free so scripts/render-diagrams.ts can run it.
 */
import { architectureManifest } from "../data/architecture-manifest.ts";
import { ASSURANCE_LABEL, assuranceFor } from "./assurance.ts";
import type { DiagramModel } from "./model.ts";

const SCENE_TITLE: Record<DiagramModel["scene"], string> = {
	"cold-open": "the cold open",
	fleet: "The Fleet",
	spine: "The Spine",
	safety: "The Safety Layers",
	finale: "The Fleet in Motion",
	hub: "The Hub",
	coda: "Coda",
};

function section(model: DiagramModel, index: number): string {
	const number = String(index + 1).padStart(2, "0");
	return [
		`## ${number} · ${model.title}`,
		"",
		"<picture>",
		`  <source srcset="../public/diagrams/${model.id}-deck.svg" media="(prefers-color-scheme: dark)">`,
		`  <img src="../public/diagrams/${model.id}-paper.svg" alt="${model.ariaLabel.replaceAll('"', "&quot;")}">`,
		"</picture>",
		"",
		model.figcaption,
		"",
		`Verify: ${model.verify}.`,
		"",
		`Claims: ${model.claims.map((c) => `\`${c}\``).join(", ")}. Assurance: ${ASSURANCE_LABEL[assuranceFor(model.claims)].toLowerCase()}. Scene: ${SCENE_TITLE[model.scene]}.`,
		"",
	].join("\n");
}

export function renderDocs(models: readonly DiagramModel[]): string {
	const policy = Object.entries(architectureManifest.claim_policy)
		.sort(([a], [b]) => a.localeCompare(b))
		.map(
			([assurance, text]) =>
				`- **${ASSURANCE_LABEL[assurance as keyof typeof ASSURANCE_LABEL]}**: ${text}`,
		)
		.join("\n");
	const head = [
		"# Mechanism diagrams",
		"",
		"<!-- Generated by scripts/render-diagrams.ts from src/diagrams/. Do not edit; run pnpm diagrams. -->",
		"",
		`${models.length} pictures of how the Operator OS works, drawn from the same closed data the`,
		"explainer replays. Each one lives in a scene's \"go deeper\" panel and here, as a",
		"static file. This page and the files under `public/diagrams/` are generated from",
		"`src/diagrams/` by `pnpm diagrams`; `src/diagrams/render.test.ts` and CI fail if a",
		"committed file no longer matches a fresh render, and `src/diagrams/facts.test.ts`",
		"fails if a printed figure no longer matches `src/data/dataset.json`.",
		"",
		"## What a diagram promises",
		"",
		"Every diagram wears the assurance level of the weakest architecture claim it",
		"depicts, taken from",
		"[`public/architecture-manifest-v1.json`](../public/architecture-manifest-v1.json):",
		"",
		policy,
		"",
		"Every count and clock time on a diagram is computed from the dataset or the",
		"vocabularies at build time; the in-app figure and the file here are rendered",
		"from one model per diagram, so they cannot say different things.",
		"",
	].join("\n");
	const tail = [
		"## Regenerating",
		"",
		"```sh",
		"pnpm diagrams   # rewrites public/diagrams/*.svg and this page from src/diagrams/",
		"pnpm test       # fails if a committed file or a printed fact has drifted",
		"```",
		"",
	].join("\n");
	return `${head}\n${models.map(section).join("\n")}\n${tail}`;
}
